"""resources table

Revision ID: 36fff97199a0
Revises: 
Create Date: 2020-03-24 22:05:14.154330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36fff97199a0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=128), nullable=True),
    sa.Column('tag', sa.String(length=128), nullable=True),
    sa.Column('link', sa.Text(), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('show', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resource_date_added'), 'resource', ['date_added'], unique=False)
    op.create_index(op.f('ix_resource_link'), 'resource', ['link'], unique=True)
    op.create_index(op.f('ix_resource_source'), 'resource', ['source'], unique=False)
    op.create_index(op.f('ix_resource_tag'), 'resource', ['tag'], unique=False)
    op.create_index(op.f('ix_resource_title'), 'resource', ['title'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resource_title'), table_name='resource')
    op.drop_index(op.f('ix_resource_tag'), table_name='resource')
    op.drop_index(op.f('ix_resource_source'), table_name='resource')
    op.drop_index(op.f('ix_resource_link'), table_name='resource')
    op.drop_index(op.f('ix_resource_date_added'), table_name='resource')
    op.drop_table('resource')
    # ### end Alembic commands ###
