"""empty message

Revision ID: 7b9fc3a46890
Revises: e1f7bde1aa20
Create Date: 2020-03-27 18:42:08.209872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b9fc3a46890'
down_revision = 'e1f7bde1aa20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resource_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'resources', ['resource_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('resource_id')

    # ### end Alembic commands ###
