"""empty message

Revision ID: e1f7bde1aa20
Revises: 09fd72b6648e
Create Date: 2020-03-27 18:18:50.324456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1f7bde1aa20'
down_revision = '09fd72b6648e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)

    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.drop_index('ix_resources_upvotes')
        batch_op.drop_column('upvotes')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upvotes', sa.INTEGER(), nullable=True))
        batch_op.create_index('ix_resources_upvotes', ['upvotes'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    # ### end Alembic commands ###
